// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChdrCxgA-Ki3B0LZ6aU3Qcz2L1JlcZktA',
    appId: '1:82610117027:web:85f38aadb9106f90c02216',
    messagingSenderId: '82610117027',
    projectId: 'armcold',
    authDomain: 'armcold.firebaseapp.com',
    storageBucket: 'armcold.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9oggIsipeDCTDCuVLANrXOz8YeEsXk70',
    appId: '1:82610117027:android:93da95404714185ec02216',
    messagingSenderId: '82610117027',
    projectId: 'armcold',
    storageBucket: 'armcold.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzqGIK-YpzwRGd4dtt8AOEs5eej3tDKLY',
    appId: '1:82610117027:ios:73d50937a3ccf9d8c02216',
    messagingSenderId: '82610117027',
    projectId: 'armcold',
    storageBucket: 'armcold.firebasestorage.app',
    iosBundleId: 'com.example.crestarmcold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzqGIK-YpzwRGd4dtt8AOEs5eej3tDKLY',
    appId: '1:82610117027:ios:73d50937a3ccf9d8c02216',
    messagingSenderId: '82610117027',
    projectId: 'armcold',
    storageBucket: 'armcold.firebasestorage.app',
    iosBundleId: 'com.example.crestarmcold',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChdrCxgA-Ki3B0LZ6aU3Qcz2L1JlcZktA',
    appId: '1:82610117027:web:313a133f32bdb8e3c02216',
    messagingSenderId: '82610117027',
    projectId: 'armcold',
    authDomain: 'armcold.firebaseapp.com',
    storageBucket: 'armcold.firebasestorage.app',
  );
}
